### PR TITLE
fix version masking

### PR DESCRIPTION
**Pull request by conradludgate**
I noticed when testing that my recipe.json was being rebuilt when I updated my package version number

### CODE REVIEW

**Comment by conradludgate** [comment]
Seems to also be included in the Cargo.lock file, and there's currently no logic to mask it there. Should that also be done?

**Comment by LukeMathWalker** [comment]
I am not 100% sure on what behaviour you are changing - isn't the old `main` version equivalent to your branch version?

**Comment by conradludgate** [comment]
So the code I replaced makes it seem that the Cargo.toml `package.version` value should be replaced with `0.1.0`, but when I run `cargo chef prepare`, it is not getting replaced and the resulting `recipe.json` file is different (meaning my cache is invalidated and needs a rebuild of dependencies)

**Comment by LukeMathWalker** [comment]
Understood - would you mind adding a test, so that we do not regress on this functionality going forward?

**Comment by LukeMathWalker** [comment]
Almost there - just run `cargo fmt` and then we can merge 😁

**Comment by conradludgate** [comment]
> Almost there - just run `cargo fmt` and then we can merge grin

There's always something :facepalm:

**Pull request merged**
